# Generated by Django 3.0.5 on 2020-04-26 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bust', models.FloatField()),
                ('waist', models.FloatField()),
                ('hip', models.FloatField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
