# Generated by Django 3.0.5 on 2020-04-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionmodel',
            name='display_image',
            field=models.ImageField(default='./images/placeholder.jpg', upload_to=None),
        ),
    ]
